

`define state_arpel_width 7 
`define state_arpel_width_minus1 6   
 
`define reset_arpel_state                        `state_arpel_width'd0
`define check_enable_arpel_state                 `state_arpel_width'd1
`define chip_select_high_to_low_arpel_state      `state_arpel_width'd2
`define convst_low_arpel_state                   `state_arpel_width'd3
`define busy_wait_arpel_state                    `state_arpel_width'd4
`define busy_high_arpel_state                    `state_arpel_width'd5
`define ch1_data_read_150_arpel_state            `state_arpel_width'd6
`define ch1_data_read_151_arpel_state            `state_arpel_width'd7
`define ch1_data_read_140_arpel_state            `state_arpel_width'd8
`define ch1_data_read_141_arpel_state            `state_arpel_width'd9
`define ch1_data_read_130_arpel_state            `state_arpel_width'd10
`define ch1_data_read_131_arpel_state            `state_arpel_width'd11
`define ch1_data_read_120_arpel_state            `state_arpel_width'd12
`define ch1_data_read_121_arpel_state            `state_arpel_width'd13
`define ch1_data_read_110_arpel_state            `state_arpel_width'd14
`define ch1_data_read_111_arpel_state            `state_arpel_width'd15
`define ch1_data_read_100_arpel_state            `state_arpel_width'd16
`define ch1_data_read_101_arpel_state            `state_arpel_width'd17
`define ch1_data_read_90_arpel_state             `state_arpel_width'd18
`define ch1_data_read_91_arpel_state             `state_arpel_width'd19
`define ch1_data_read_80_arpel_state             `state_arpel_width'd20
`define ch1_data_read_81_arpel_state             `state_arpel_width'd21
`define ch1_data_read_70_arpel_state             `state_arpel_width'd22
`define ch1_data_read_71_arpel_state             `state_arpel_width'd23
`define ch1_data_read_60_arpel_state             `state_arpel_width'd24
`define ch1_data_read_61_arpel_state             `state_arpel_width'd25
`define ch1_data_read_50_arpel_state             `state_arpel_width'd26
`define ch1_data_read_51_arpel_state             `state_arpel_width'd27
`define ch1_data_read_40_arpel_state             `state_arpel_width'd28
`define ch1_data_read_41_arpel_state             `state_arpel_width'd29
`define ch1_data_read_30_arpel_state             `state_arpel_width'd30
`define ch1_data_read_31_arpel_state             `state_arpel_width'd31
`define ch1_data_read_20_arpel_state             `state_arpel_width'd32
`define ch1_data_read_21_arpel_state             `state_arpel_width'd33
`define ch1_data_read_10_arpel_state             `state_arpel_width'd34
`define ch1_data_read_11_arpel_state             `state_arpel_width'd35
`define ch1_data_read_00_arpel_state             `state_arpel_width'd36
`define ch1_data_read_01_arpel_state             `state_arpel_width'd37
`define wait_next_channel_arpel_state            `state_arpel_width'd38
`define ch2_data_read_150_arpel_state            `state_arpel_width'd39
`define ch2_data_read_151_arpel_state            `state_arpel_width'd40
`define ch2_data_read_140_arpel_state            `state_arpel_width'd41
`define ch2_data_read_141_arpel_state            `state_arpel_width'd42
`define ch2_data_read_130_arpel_state            `state_arpel_width'd43
`define ch2_data_read_131_arpel_state            `state_arpel_width'd44
`define ch2_data_read_120_arpel_state            `state_arpel_width'd45
`define ch2_data_read_121_arpel_state            `state_arpel_width'd46
`define ch2_data_read_110_arpel_state            `state_arpel_width'd47
`define ch2_data_read_111_arpel_state            `state_arpel_width'd48
`define ch2_data_read_100_arpel_state            `state_arpel_width'd49
`define ch2_data_read_101_arpel_state            `state_arpel_width'd50
`define ch2_data_read_90_arpel_state             `state_arpel_width'd51
`define ch2_data_read_91_arpel_state             `state_arpel_width'd52
`define ch2_data_read_80_arpel_state             `state_arpel_width'd53
`define ch2_data_read_81_arpel_state             `state_arpel_width'd54
`define ch2_data_read_70_arpel_state             `state_arpel_width'd55
`define ch2_data_read_71_arpel_state             `state_arpel_width'd56
`define ch2_data_read_60_arpel_state             `state_arpel_width'd57
`define ch2_data_read_61_arpel_state             `state_arpel_width'd58
`define ch2_data_read_50_arpel_state             `state_arpel_width'd59
`define ch2_data_read_51_arpel_state             `state_arpel_width'd60
`define ch2_data_read_40_arpel_state             `state_arpel_width'd61
`define ch2_data_read_41_arpel_state             `state_arpel_width'd62
`define ch2_data_read_30_arpel_state             `state_arpel_width'd63
`define ch2_data_read_31_arpel_state             `state_arpel_width'd64
`define ch2_data_read_20_arpel_state             `state_arpel_width'd65
`define ch2_data_read_21_arpel_state             `state_arpel_width'd66
`define ch2_data_read_10_arpel_state             `state_arpel_width'd67
`define ch2_data_read_11_arpel_state             `state_arpel_width'd68
`define ch2_data_read_00_arpel_state             `state_arpel_width'd69
`define ch2_data_read_01_arpel_state             `state_arpel_width'd70
`define chip_select_low_to_high_arpel_state      `state_arpel_width'd71
`define done_arpel_state                         `state_arpel_width'd72